name: ${PROJECT_NAME:-DEV-app-demo}

services:
  dev-app-demo:
    container_name: ${CONTAINER_NAME:-dev-app-demo}
    hostname: ${CONTAINER_NAME:-dev-app-demo}
    build:
      context: ../../
      dockerfile: tool/dev-demo.Dockerfile
      args:
        - ENABLE_CODE_BUILD=false
        # - PROFILE_LOCALIZE=${PROFILE_LOCALIZE:-default}
      pull: true
    restart: unless-stopped
    # env_file: ["../credentials/DEV-app-demo.env"]
    environment:
      # - ENV_PROFILE=${ENV_PROFILE:-DEV}
      - PROFILE_LOCALIZE=${PROFILE_LOCALIZE:-default}
      - PYTHONPATH=/root/app/pkg:/root/app/src:/root/app/notebook
    user: "0:0"
    ports: [ "${PORT_APP:-9000}:9000", "${PORT_WEB:-3000}:3000" ]
    volumes:
      - ../../:/root/app:rw
      # AI4Coding tools:
      - "$HOME/.claude:/root/.claude:rw"
      - "$HOME/.codex:/root/.codex:rw"
      - "$HOME/.copilot:/root/.copilot:rw"
      - "$HOME/.gemini:/root/.gemini:rw"
    working_dir: /root/app
    command: "tail -f /dev/null"
