name: ${PROJECT_NAME:-DEV-app-demo}

services:
  dev-app-demo:
    container_name: ${CONTAINER_NAME:-dev-app-demo}
    hostname: ${CONTAINER_NAME:-dev-app-demo}
    build:
      context: ../../
      dockerfile: src/dev-demo.Dockerfile
      args:
        - ENABLE_CODE_BUILD=false
        # - PROFILE_LOCALIZE=${PROFILE_LOCALIZE:-default}
      pull: true
    restart: unless-stopped
    # env_file: ["../credentials/DEV-app-demo.env"]
    environment:
      # - PROFILE_ENV=${PROFILE_ENV:-DEV}
      - PROFILE_LOCALIZE=${PROFILE_LOCALIZE:-default}
      - PYTHONPATH=/workspace/pkg:/workspace/src:/workspace/notebook
      - HOME=/home/${CONTAINER_UID:-0}
    user: "${CONTAINER_UID:-0}:${CONTAINER_GID:-0}"
    ports: ["${PORT_APP:-9000}:9000", "${PORT_WEB:-3000}:3000"]
    working_dir: /workspace
    volumes:
      - ../../:/workspace:rw
      # SSH
      - "$HOME/.ssh:/home/${CONTAINER_UID:-0}/.ssh:rw"
      # AI4Coding tools:
      - "$HOME/.claude:/home/${CONTAINER_UID:-0}/.claude:rw"
      - "$HOME/.codex:/home/${CONTAINER_UID:-0}/.codex:rw"
      - "$HOME/.copilot:/home/${CONTAINER_UID:-0}/.copilot:rw"
      - "$HOME/.gemini:/home/${CONTAINER_UID:-0}/.gemini:rw"
    command: "tail -f /dev/null"
